= Rest API Spec using springdoc
Sasi Peri <sasi.peri@cardinalhealth.com>
v1.0, 2020-10-16

:toc:

= Introduction
This is a refernce implementation show casing best practices using spring doc for generating api specs for contract driven development (and testing). Salient aspects are documented here.

= Steps
<1> Get dependencies as detailed in the dependencies section.
<2> Add generic configuration (security policies, api info etc..) as called out code section (via spring configuration).
<3> Run the generate api gradle task `gradle clean generateOpenApiDocs` to generate documentation. And openapi.json should be available under the gradle build folder.
<4> Using the swaggor editor, inspect documentation "auto generated" by spring-doc.
<5> If you followed best practices and spring/java guidelines for builidng Rest Apis (important ones are called in the "Pre-requisites" section), already the document (opanApi Spec) generated should be good enough.
<6> Add springdoc openapi annotation into code, if the generated documentation is not enough? Which could be due to not following best practices OR due to legitamate excepions called out under " Handling the specific overrides"

= Pre-requisites (good rest-api pracices)

IMPORTANT: Springdoc is able to introspect the code, and is able to produce good documenation, with no additional coding. However. for the springdoc to auto-generate good documentation, before overriding with specific annotations, developers are required to follow, the following REST-API, Sping and Java coding practices.

. Good and meaning naming conventions of the variables, method names and models (pers Sun/Oracle guidelines)
. Exceptions and HTTP Responses (for global nature, applicable to all endpoints) handled via Rest Controller Advices
. All validations handled via JSR303 spec. For example
.. Plain POJOS (model/dto etc..) validated via javax.validator
.. JPA Entirties and such via hibernate validator

= Code details
== Dependencies
They are shown in the code snippet below. Details of which are below.

* *Required:*  
** sprindoc-ui depedency *alone* is enough to get core opanAPI spec generation and swagger-gui generation. 
** If GUI is *not* needed then one of mvc-core or webflux-core are required as depedencies.
** If the Rest API is built (system api to expose domains) using Spring-Data-Rest you also need to add springdoc-openapi-data-rest, so that springdoc will be able to introspect the JPA Repositories and auto generate documenation for you.
* *Opional (security):* Spring doc security plugin is needed, so as to ignore @AuthenticationPrincipal in case its used on REST Controllers and any possible errors that may occur (due to lack of oidc/sso during testing)
* *Plugins:*  The springdoc doc gradle/maven plugin is needed to generate json and yaml OpenAPI description during build time. The plugin works during integration-tests phase, and generate the OpenAPI description. The plugin works in conjunction with spring-boot-maven plugin.

=== dependencies gradle
[source,groovy]
----
implementation 'org.springdoc:springdoc-openapi-ui:1.4.8'. // for both mvc core and ui
implementation 'org.springdoc:springdoc-openapi-security:1.4.8'	//security of @AuthenticationPrincipal is used
----

=== gradle plugin - groovy DSL
[source,groovy]
----
id "com.github.johnrengelman.processes" version "0.5.0"
id 'org.springdoc.openapi-gradle-plugin' version '1.3.0'
----

== Global configuration

`include::/cah-ea-ref-openapi-springdoc/blob/3779a91d6aa1f62fab0e58548fe034e6e1ca7f87/src/main/java/com/example/demo/config/OpenAPIConfig.java#L22-L96`

`include::./src/main/java/com/example/demo/config/OpenAPIConfig.java#L22-L96`

[source,java]
----
https://github.com/cah-venkatasuryasasikala-peri/cah-ea-ref-openapi-springdoc/blob/3779a91d6aa1f62fab0e58548fe034e6e1ca7f87/src/main/java/com/example/demo/config/OpenAPIConfig.java#L22-L96
----
